### ISSUE TITLE
how can i add a field,such as description

### ISSUE THREAD

**Issue by likelxl** [alpertuna/vim-header#44]
as the title desc,what can i do

**Comment by alpertuna** [comment]
It doesn't support custom fields.
For file specific fields, you can add it to header manually. Plugin wont touch them.

**Comment by samerickson** [comment]
A description is something that changes from file to file, this plugin focuses on things that do not change from file to file of the same type or extension. Since you would have to hand-write the description if and when you want one, and once it is written it it doesn't need any form of automatic updating, like the:
* filename
* file path
*modification author and date
it seems pointless to add it to this plugin as descriptions are so different from all other elements handled by this plugin. Amazing work @alpertuna by the way.
